# Generated by Django 5.1.3 on 2024-11-28 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.CharField(help_text='Įveskite automobilio pagaminimo metus', max_length=4, verbose_name='AUTOMOBILIO_METAI')),
                ('marke', models.CharField(help_text='Įveskite automobilio markę', max_length=20, verbose_name='AUTOMOBILIO_MARKĖ')),
                ('modelis', models.CharField(help_text='Įveskite automobilio modelį pvz. A4, M3, F10, G30, GS, LS', max_length=20, verbose_name='AUTOMOBILIO_MODELIS')),
                ('variklis', models.CharField(help_text='Įveskite varikio parametrus: litražą, kilovatus, kuro tipą', max_length=50, verbose_name='VARIKLIS')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilių modeliai',
                'ordering': ['marke'],
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą', max_length=200, unique=True, verbose_name='PASLAUGA')),
                ('kaina', models.DecimalField(decimal_places=2, help_text='Įveskite paslaugos kainą', max_digits=10, verbose_name='PASLAUGOS_KAINA')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
                'ordering': ['pavadinimas'],
            },
        ),
        migrations.CreateModel(
            name='AutomobilisKlientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Įveskite automobilio valstybinius numerius', max_length=15, unique=True, verbose_name='VALSTYBINIS_NUMERIS')),
                ('vin_kodas', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=100, unique=True, verbose_name='VIN_KODAS')),
                ('klientas', models.CharField(help_text='Įveskite kliento vardą ir pavardę', max_length=50, verbose_name='KLIENTO_VARDAS_PAVARDĖ')),
                ('modelis', models.ForeignKey(help_text='Pasirinkite automobilį', on_delete=django.db.models.deletion.CASCADE, to='Autoservisas.automobiliomodelis')),
            ],
            options={
                'verbose_name': 'Kliento automobilis',
                'verbose_name_plural': 'Klientų automobiliai',
                'ordering': ['klientas'],
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Įveskite užsakymo datą', verbose_name='UŽSAKYMO_DATA')),
                ('automobilis', models.ForeignKey(help_text='Pasirinkite kliento automobilį', on_delete=django.db.models.deletion.CASCADE, to='Autoservisas.automobilisklientas')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(help_text='Įveskite paslaugų kiekį', verbose_name='KIEKIS')),
                ('paslauga', models.ForeignKey(help_text='Pasirinkite paslaugas', on_delete=django.db.models.deletion.CASCADE, to='Autoservisas.paslauga')),
                ('uzsakymas', models.ForeignKey(help_text='Įveskite užsakymo ID', on_delete=django.db.models.deletion.CASCADE, to='Autoservisas.uzsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymo eilutės',
            },
        ),
    ]
