# Generated by Django 5.1.3 on 2024-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='statusas',
            field=models.CharField(blank=True, choices=[('L', 'Laukiama'), ('V', 'Vykdoma'), ('A', 'Atlikta')], default='L', help_text='Pasirinkite užsakymo statusą', max_length=10),
        ),
    ]
