# Generated by Django 5.1.3 on 2024-12-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoservisas', '0002_uzsakymas_statusas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'ordering': ['statusas'], 'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
            field=models.ForeignKey(help_text='Pasirinkite uzsakyma', on_delete=django.db.models.deletion.CASCADE, to='Autoservisas.uzsakymas'),
        ),
    ]
